version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains the airbnb listings
    columns:
      - name: listing_id
        description: Table Pk
        tests:
          - unique
          - not_null
      - name: host_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: Type of rooom (appartment, single room)
        tests:
          - accepted_values:
              values:
                ["Entire home/apt", "Private room", "Shared room", "Hotel room"]
      - name: minimum_nights
        description: '{{doc("dim_listing_cleansed__minimum_nights")}}'
        tests:
          - positive_value
